<table>
    <thead>
    <tr>
        <th>Servidor_id</th>
        <th>Identificador</th>
        <th>Servidor - Direccion</th>
        <th>Puerto</th>
        <th>Cifrado</th>
    </tr>
    </thead>
    <tbody>
        <tr>
            <td>1</td>
            <td>Test</td>
            <td>192.168.100.1</td>
            <td>280</td>
            <td>TBA</td>
        </tr>
    </tbody>
</table>