<table>
    <thead>
    <tr>
        <th>Equipo_id</th>
        <th>Tipo_id</th>
        <th>Identificador</th>
        <th>Clave</th>
        <th>Clave de recuperacion</th>
    </tr>
    </thead>
    <tbody>
        <tr>
            <td>1</td>
            <td>1</td>
            <td>Equipo1</td>
            <td>CBDA38D4-AAAA-BBBB-CCCC-F225A1D1AF12</td>
            <td>656227-RRRRRR-FFFFFF-SSSSSS-044011-397595-216414-003080</td>
        </tr>
    </tbody>
</table>